# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-24 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0002_candidato_porcentaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='porcentaje',
        ),
    ]
